language: python
python:
 - "2.7"
sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo apt-get -y install python-qt4 python-scapy python-nmap
 - chmod a+x installer.sh
 - ./installer.sh --install

install:
 - pip install -r requirements.txt
script: nosetests